### PR TITLE
Replace title of website from Tvarit AI to Tvarit Industrial AI

### PR DESCRIPTION
**Pull request by digitalwebair**
#394

### CODE REVIEW

**Comment by rkamath3** [comment]
@Sumeshks29 is there a way to push it to beta and test ?

**Comment by Sumeshks29** [comment]
> @Sumeshks29 is there a way to push it to beta and test ?

Yes, I will checkout this PR  on beta server.

**Comment by rkamath3** [comment]
image
I still see JS errors

**Comment by rkamath3** [comment]
image
Still missing alt tag

**Comment by rkamath3** [comment]
image

**Pull request closed without merging**
