### PR TITLE
Pushed Hannover event to Past Event section on the News page(Both eng…

### PR DESCRIPTION
**Pull request by lokeshmittaldev**
Fixes: #693

### CODE REVIEW

**Comment by Poorvasisodia** [comment]
@lokeshmittaldev please check again..
The image file is too big that you have put in the past event section.
Also the sign up button is not required. Please remove it.

**Comment by Poorvasisodia** [comment]
@starkblaze01 good to go live!

**Comment by Poorvasisodia** [comment]
@starkblaze01  Please hold it. I will update you

**Comment by starkblaze01** [comment]
Shifted to #733

**Pull request closed without merging**
