### PR TITLE
Added tracking code in german pages

### PR DESCRIPTION
**Pull request by lokeshmittaldev**
Fixes: #594

### CODE REVIEW

**Comment by Sumeshks29** [comment]
@lokeshmittaldev  There are commits for other issues in this PR, please fix

**Comment by Poorvasisodia** [comment]
@Sumeshks29 I have asked him to do the required changes. He will update

**Comment by lokeshmittaldev** [comment]
@Sumeshks29  can you please send me details of conflicts. So i can resolve those. Current i can not see any conflict here.

**Comment by Sumeshks29** [comment]
@lokeshmittaldev  Its not about the conflict, its regarding the PR content and files changed. This PR has changes that are required for another issue. As I had mentioned earlier, a PR should contain changes corresponding to only one issue and not multiple issues. please refer readme.

**Pull request closed without merging**
