### PR TITLE
Updated auto email formatting-Contact forms

### PR DESCRIPTION
**Pull request by lokeshmittaldev**
Fixes: #577

### CODE REVIEW

**Comment by Sumeshks29** [comment]
@Poorvasisodia Is there any changes needed to be done here?

**Comment by Poorvasisodia** [comment]
@Sumeshks29 ..Yes. There was some error occurring in the submission part. Lokesh will again rectify that and revert today!

**Comment by Poorvasisodia** [comment]
@lokeshmittaldev Hi Lokesh..as discussed yesterday, plz look into the matter. We can't submit the form-hence no email acknowledgement to review. Let me know once it is done.!

**Comment by lokeshmittaldev** [comment]
Hello Poorva

I have fixed the issue and committed the code. Please check this.

Thanks

**Comment by Poorvasisodia** [comment]
@lokeshmittaldev Please find points as below to modify this further
1. Please reduce the image size to a certain extent. Its too big and occupying the maximum space in an email while the main information goes completely unnoticed. It should be in the center or on the right corner in a smaller size but should not let the message wrap.
2. Please change the address in the email signature(exactly below the signature image)
Tvarit GmbH
Hanauer Landstraße 521,
60386 Frankfurt am Main, Germany (and then followed by the rest of the text)
3. The font alignment.

**Comment by lokeshmittaldev** [comment]
Hello Poorva

I have made the changes and committed the code. Please check this.

Thanks

**Pull request merged**
